import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import ConicPolygonGeometry from 'three-conic-polygon-geometry';
import {geoContains} from 'd3-geo';
import {sunVector,moonState} from './astronomy.mjs';
const radians=Math.PI/180;
const xyz=(lon:number,lat:number,r=1)=>new THREE.Vector3(r*Math.cos(lat*radians)*Math.sin(lon*radians),r*Math.sin(lat*radians),r*Math.cos(lat*radians)*Math.cos(lon*radians));
export async function mountGlobe(shell:HTMLElement){
 const stage=shell.querySelector<HTMLElement>('.globe-stage')!, status=shell.querySelector<HTMLElement>('.globe-status')!, tooltip=shell.querySelector<HTMLElement>('.globe-tooltip')!,pause=shell.querySelector<HTMLButtonElement>('[data-pause]')!,moonCaption=shell.querySelector<HTMLElement>('.moon-caption')!;
 const catalog=JSON.parse(shell.querySelector('[data-globe-data]')!.textContent!);const byCode=new Map(catalog.map(c=>[c.code,c]));
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');let running=!reduced.matches,visible=true,disposed=false,lastTime=0,hovered:any=null,focusMesh:THREE.Group|null=null,focusScale=1,frame=0;
 const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(38,1,.1,100);camera.position.copy(xyz(22,24,3.25));scene.add(camera);
 const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});renderer.setClearColor(0x08151c,0);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;
 renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','Gaublys. Rodyklėmis pasukite, pliusu ar minusu keiskite mastelį. Šalį pasirinkite pele arba naudokite paiešką.');stage.append(renderer.domElement);
 const controls=new OrbitControls(camera,renderer.domElement);controls.enablePan=false;controls.enableDamping=!reduced.matches;controls.dampingFactor=.08;controls.minDistance=1.7;controls.maxDistance=6.4;controls.rotateSpeed=.45;controls.zoomSpeed=.6;controls.autoRotate=running;controls.autoRotateSpeed=.23;
 controls.minPolarAngle=.05;controls.maxPolarAngle=Math.PI-.05;
 const updatePause=()=>{pause.textContent=running?'Pauzė Ⅱ':'Sukti ↻';pause.setAttribute('aria-label',running?'Sustabdyti sukimąsi':'Pradėti sukimąsi');pause.setAttribute('aria-pressed',String(!running));controls.autoRotate=running;};
 const stop=()=>{running=false;updatePause();};controls.addEventListener('start',stop);pause.addEventListener('click',()=>{running=!running;updatePause();});
 const resize=()=>{const {width,height}=stage.getBoundingClientRect();camera.aspect=width/height;camera.updateProjectionMatrix();renderer.setSize(width,height,false);};const ro=new ResizeObserver(resize);ro.observe(stage);resize();
 let earth:THREE.Mesh;let geography:any;let moon:THREE.Mesh|null=null;let moonLoading=false;
 const loader=new THREE.TextureLoader();const timed=<T>(p:Promise<T>)=>new Promise<T>((resolve,reject)=>{const t=setTimeout(()=>reject(Error('Globe assets timed out')),15000);p.then(x=>{clearTimeout(t);resolve(x)},e=>{clearTimeout(t);reject(e)});});
 try{
  const [day,night,geo]=await timed(Promise.all([loader.loadAsync('/textures/earth-day.webp'),loader.loadAsync('/textures/earth-night.webp'),fetch('/geo/countries.geojson',{signal:AbortSignal.timeout(15000)}).then(r=>{if(!r.ok)throw Error('Geography failed');return r.json();})]));geography=geo;
  day.colorSpace=THREE.SRGBColorSpace;night.colorSpace=THREE.SRGBColorSpace;
  const material=new THREE.ShaderMaterial({uniforms:{dayMap:{value:day},nightMap:{value:night},sun:{value:new THREE.Vector3(...sunVector())}},vertexShader:`varying vec2 vUv; varying vec3 vN; void main(){vUv=uv;vN=normalize(mat3(modelMatrix)*normal);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`uniform sampler2D dayMap;uniform sampler2D nightMap;uniform vec3 sun;varying vec2 vUv;varying vec3 vN;void main(){float light=dot(normalize(vN),sun);float day=smoothstep(-.14,.20,light);vec3 terrain=texture2D(dayMap,vUv).rgb;vec3 cities=texture2D(nightMap,vUv).rgb;vec3 color=terrain*(.055+day*(.40+.60*max(light,0.)))+cities*(1.-smoothstep(-.22,.10,light))*1.4;gl_FragColor=vec4(color,1.);#include <colorspace_fragment>\n}`.replace(';#include',';\n#include')});
  earth=new THREE.Mesh(new THREE.SphereGeometry(1,96,64),material);earth.rotation.y=-Math.PI/2;scene.add(earth);
  const atmosphere=new THREE.Mesh(new THREE.SphereGeometry(1.026,64,48),new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.BackSide,uniforms:{},vertexShader:`varying vec3 vNormal;varying vec3 vPosition;void main(){vNormal=normalize(normalMatrix*normal);vec4 p=modelViewMatrix*vec4(position,1.);vPosition=p.xyz;gl_Position=projectionMatrix*p;}`,fragmentShader:`varying vec3 vNormal;varying vec3 vPosition;void main(){float rim=pow(1.-abs(dot(normalize(vNormal),normalize(-vPosition))),3.);gl_FragColor=vec4(.20,.52,.72,rim*.46);}`}));scene.add(atmosphere);
  // All outlines are one draw call; no thousands of per-country meshes at startup.
  const points:number[]=[];
  for(const f of geo.features){const polys=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;for(const poly of polys)for(const ring of poly){for(let i=1;i<ring.length;i++){const a=xyz(...ring[i-1],1.003),b=xyz(...ring[i],1.003);points.push(...a.toArray(),...b.toArray());}}}
  const borderGeometry=new THREE.BufferGeometry();borderGeometry.setAttribute('position',new THREE.Float32BufferAttribute(points,3));scene.add(new THREE.LineSegments(borderGeometry,new THREE.LineBasicMaterial({color:0xb1c5bd,transparent:true,opacity:.29})));
  function countryMesh(feature:any,color:number,opacity:number){const group=new THREE.Group(),polys=feature.geometry.type==='Polygon'?[feature.geometry.coordinates]:feature.geometry.coordinates;for(const poly of polys){const geom=new ConicPolygonGeometry(poly,1.004,1.008,false,true,true,4);group.add(new THREE.Mesh(geom,new THREE.MeshBasicMaterial({color,transparent:true,opacity,depthWrite:false,side:THREE.DoubleSide})));}return group;}
  for(const f of geo.features){const c:any=byCode.get(f.properties.alpha2);if(c?.visited)scene.add(countryMesh(f,0xcda773,.7));}
  // Public debug state is deliberately non-sensitive and helps QA distinguish a rendered globe from a poster.
  shell.dataset.ready='true';shell.dataset.renderer='webgl2';for(const b of shell.querySelectorAll<HTMLButtonElement>('.globe-controls button'))b.disabled=false;updatePause();
  const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let press={x:0,y:0};
  function picked(e:PointerEvent){const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObject(earth)[0];if(!hit)return null;const p=hit.point.clone().normalize();const coord=[Math.atan2(p.x,p.z)/radians,Math.asin(p.y)/radians];return geo.features.find(f=>byCode.has(f.properties.alpha2)&&geoContains(f,coord))||null;}
  function clearHover(){tooltip.hidden=true;hovered=null;if(focusMesh){scene.remove(focusMesh);focusMesh.traverse((o:any)=>{o.geometry?.dispose();o.material?.dispose();});focusMesh=null;}}
  renderer.domElement.addEventListener('pointermove',e=>{if(e.buttons)return;const f=picked(e);if(!f){clearHover();return;}const c:any=byCode.get(f.properties.alpha2);const rect=shell.getBoundingClientRect();tooltip.textContent=c.name+(c.hasStories?' · atverti istorijas':'');tooltip.style.left=Math.min(Math.max(85,e.clientX-rect.left),rect.width-85)+'px';tooltip.style.top=(e.clientY-rect.top-12)+'px';tooltip.hidden=false;if(f!==hovered){if(focusMesh){scene.remove(focusMesh);focusMesh.traverse((o:any)=>{o.geometry?.dispose();o.material?.dispose();});}hovered=f;focusScale=1;focusMesh=countryMesh(f,0xd4ae7a,.67);scene.add(focusMesh);shell.dataset.hoverCountry=c.code;}});
  renderer.domElement.addEventListener('pointerleave',()=>{clearHover();delete shell.dataset.hoverCountry;});
  renderer.domElement.addEventListener('pointerdown',e=>{press={x:e.clientX,y:e.clientY};});renderer.domElement.addEventListener('pointerup',e=>{if(Math.hypot(e.clientX-press.x,e.clientY-press.y)>7)return;const f=picked(e),c:any=f&&byCode.get(f.properties.alpha2);if(c)location.href=c.href;});
  const zoom=(factor:number)=>{stop();camera.position.multiplyScalar(factor);const len=THREE.MathUtils.clamp(camera.position.length(),controls.minDistance,controls.maxDistance);camera.position.setLength(len);controls.update();};
  shell.querySelector('[data-zoom-in]')!.addEventListener('click',()=>zoom(.80));shell.querySelector('[data-zoom-out]')!.addEventListener('click',()=>zoom(1.25));shell.querySelector('[data-home]')!.addEventListener('click',()=>{stop();camera.position.copy(xyz(22,24,3.25));controls.target.set(0,0,0);controls.update();});
  renderer.domElement.addEventListener('keydown',e=>{const spherical=new THREE.Spherical().setFromVector3(camera.position);if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','='].includes(e.key)){e.preventDefault();stop();if(e.key==='ArrowLeft')spherical.theta-=.12;if(e.key==='ArrowRight')spherical.theta+=.12;if(e.key==='ArrowUp')spherical.phi-=.12;if(e.key==='ArrowDown')spherical.phi+=.12;spherical.makeSafe();camera.position.setFromSpherical(spherical);if(e.key==='+'||e.key==='=')zoom(.8);if(e.key==='-')zoom(1.25);controls.update();}});
  const touch=shell.querySelector<HTMLButtonElement>('.touch-enable')!;touch.addEventListener('click',()=>{const on=touch.getAttribute('aria-pressed')!=='true';touch.setAttribute('aria-pressed',String(on));touch.textContent=on?'Baigti valdyti':'Valdyti gaublį';shell.classList.toggle('touch-active',on);stop();});
  const io=new IntersectionObserver(([e])=>{visible=e.isIntersecting;});io.observe(shell);const media=()=>{if(reduced.matches)stop();controls.enableDamping=!reduced.matches;};reduced.addEventListener('change',media);
  async function showMoon(){if(moon||moonLoading)return;moonLoading=true;try{const map=await loader.loadAsync('/textures/moon.webp');if(disposed){map.dispose();return;}map.colorSpace=THREE.SRGBColorSpace;const state=moonState();const z=2*state.fraction-1,x=Math.sqrt(Math.max(0,1-z*z))*(state.phase<.5?1:-1);const moonMaterial=new THREE.ShaderMaterial({uniforms:{map:{value:map},lightDirection:{value:new THREE.Vector3(x,0,z)}},vertexShader:`varying vec2 vUv;varying vec3 vN;void main(){vUv=uv;vN=normal;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`uniform sampler2D map;uniform vec3 lightDirection;varying vec2 vUv;varying vec3 vN;void main(){float light=max(dot(normalize(vN),lightDirection),0.);gl_FragColor=vec4(texture2D(map,vUv).rgb*(.025+light),1.);\n#include <colorspace_fragment>\n}`});moon=new THREE.Mesh(new THREE.SphereGeometry(.105,40,32),moonMaterial);moon.position.set(.38,.29,-1.8);camera.add(moon);moonCaption.querySelector('span')!.textContent=state.name+' · '+Math.round(state.fraction*100)+' % apšviesta';}catch{moonLoading=false;}}
  const updateAstronomy=()=>{material.uniforms.sun.value.set(...sunVector());const clock=shell.querySelector('[data-earth-clock]')!;clock.textContent=new Intl.DateTimeFormat('lt',{hour:'2-digit',minute:'2-digit',timeZone:'UTC'}).format(new Date())+' UTC';};const timer=setInterval(updateAstronomy,60000);
  function animate(time:number){if(disposed)return;frame=requestAnimationFrame(animate);if(!visible||document.hidden)return;if(time-lastTime<1000/30)return;const delta=Math.min((time-lastTime)/1000,.1);lastTime=time;controls.update(delta);if(focusMesh){focusScale=reduced.matches?1.025:focusScale+(1.025-focusScale)*.18;focusMesh.scale.setScalar(focusScale);}const far=camera.position.length()>4.5;shell.dataset.zoom=far?'far':'near';if(far)showMoon();if(moon)moon.visible=far;moonCaption.hidden=!far||!moon;renderer.render(scene,camera);}
  frame=requestAnimationFrame(animate);
  const cleanup=()=>{disposed=true;cancelAnimationFrame(frame);clearInterval(timer);ro.disconnect();io.disconnect();reduced.removeEventListener('change',media);controls.dispose();scene.traverse((o:any)=>{o.geometry?.dispose();if(o.material){const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats){m.uniforms?.dayMap?.value.dispose();m.uniforms?.nightMap?.value.dispose();m.uniforms?.map?.value.dispose();m.dispose();}}});renderer.dispose();};
  renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();cleanup();shell.dataset.ready='false';shell.dataset.error='contextlost';status.innerHTML='<p>3D ryšys nutrūko.</p><a href="/salys/">Tęsti šalių sąraše →</a><button type="button">Bandyti dar kartą</button>';status.querySelector('button')!.addEventListener('click',()=>location.reload());for(const b of shell.querySelectorAll<HTMLButtonElement>('.globe-controls button'))b.disabled=true;});window.addEventListener('pagehide',cleanup,{once:true});
 }catch(e){disposed=true;ro.disconnect();controls.dispose();renderer.dispose();renderer.domElement.remove();throw e;}
}
