import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {importPackage,readJson} from '../scripts/import.mjs';import {geoContains} from 'd3-geo';import {sunVector,moonState} from '../src/lib/astronomy.mjs';
async function setup(){const root=await fs.mkdtemp(path.join(os.tmpdir(),'ttj-'));await fs.mkdir(path.join(root,'content'));await fs.copyFile('content/countries.json',path.join(root,'content/countries.json'));await fs.cp('.work/demo',path.join(root,'demo'),{recursive:true});await fs.copyFile('.work/demo-package.json',path.join(root,'package.json'));return {root,p:path.join(root,'package.json')};}
async function withEnv(fn){const env=await setup();try{await fn(env);}finally{await fs.rm(env.root,{recursive:true,force:true});}}
test('Drive fixture: interruption, resume, same/new batch deduplication; no visit invented',async()=>withEnv(async({root,p})=>{
 const partial=await importPackage(p,{root,stopAfter:2});assert.equal(partial.complete,false);assert.equal(partial.processed,2);assert.equal(await fs.access(path.join(root,'content/archive.json')).then(()=>true,()=>false),false);
 const resumed=await importPackage(p,{root});assert.equal(resumed.reused,2);assert.equal(resumed.processed,4);assert.equal(resumed.complete,true);
 const repeated=await importPackage(p,{root});assert.equal(repeated.processed,0);assert.equal(repeated.reused,6);assert.equal(repeated.storyCount,3);assert.equal(repeated.assetCount,6);
 const newer=path.join(root,'second-package.json');await fs.copyFile(p,newer);assert.equal((await importPackage(newer,{root})).processed,0);
 const result=await readJson(path.join(root,'content/archive.json'));assert.deepEqual(result.visits,[]);assert(result.stories.every(s=>s.status==='draft'&&s.publishedAt===null&&s.visitDate===null));
}));
test('Manual caption, alt, order and removal survive; conflicting source is reported repeatedly',async()=>withEnv(async({root,p})=>{
 await importPackage(p,{root});const file=path.join(root,'content/archive.json');let content=await readJson(file);const gallery=content.stories[0].gallery;gallery.reverse();gallery.pop();gallery[0].caption='Rankinis užrašas';gallery[0].alt='Rankinis alternatyvus tekstas';await fs.writeFile(file,JSON.stringify(content));
 let r=await importPackage(p,{root});assert.equal(r.conflicts.length,0);assert.deepEqual((await readJson(file)).stories[0].gallery,gallery);
 const pkg=await readJson(p);pkg.stories[0].gallery[0].caption='Pakeistas šaltinis';await fs.writeFile(p,JSON.stringify(pkg));r=await importPackage(p,{root});assert.equal(r.complete,false);assert(r.conflicts.some(c=>c.field==='gallery'));assert.deepEqual((await readJson(file)).stories[0].gallery,gallery);assert.equal((await importPackage(p,{root})).complete,false);
}));
test('Changed bytes produce new URLs; missing or unsafe assets leave content unchanged',async()=>withEnv(async({root,p})=>{
 await importPackage(p,{root});const file=path.join(root,'content/archive.json'),before=await fs.readFile(file,'utf8');const pkg=await readJson(p);const asset=path.join(root,pkg.assets[0].file);await fs.writeFile(asset,(await fs.readFile(asset,'utf8')).replace('#143b42','#194b50'));const r=await importPackage(p,{root});assert.equal(r.processed,1);const after=await readJson(file);assert.notEqual(JSON.parse(before).assets[0].sha256,after.assets[0].sha256);
 const stable=await fs.readFile(file,'utf8');pkg.assets[0].file='../outside.jpg';await fs.writeFile(p,JSON.stringify(pkg));await assert.rejects(importPackage(p,{root}));assert.equal(await fs.readFile(file,'utf8'),stable);
}));
test('Originals remain unchanged and output has no EXIF; text-only story valid',async()=>withEnv(async({root,p})=>{
 const original=await fs.readFile(path.join(root,'demo/03_galerija/test-01.svg'),'utf8');await importPackage(p,{root});assert.equal(await fs.readFile(path.join(root,'demo/03_galerija/test-01.svg'),'utf8'),original);const c=await readJson(path.join(root,'content/archive.json'));assert.equal(c.stories.find(s=>s.slug==='tik-tekstas').gallery.length,0);const sharp=(await import('sharp')).default;const meta=await sharp(path.join(root,'public',c.assets[0].variants[0].src)).metadata();assert.equal(meta.format,'webp');assert.equal(meta.width,480);assert.equal(meta.exif,undefined);
}));
test('Country geometry includes Crimea in Ukraine, never Russia; count is unique 195',async()=>{const geo=await readJson('public/geo/countries.geojson');const ua=geo.features.find(f=>f.properties.alpha2==='UA'),ru=geo.features.find(f=>f.properties.alpha2==='RU');for(const p of [[34.1,44.95],[33.52,44.6],[35.38,45.03]]){assert(geoContains(ua,p));assert(!geoContains(ru,p));}const c=await readJson('content/countries.json');assert.equal(new Set(c.countries.map(c=>c.country_id)).size,195);});
test('Sun unit and longitude conventions: equinox noon at Greenwich; Moon changes over time',()=>{const noon=sunVector(new Date('2026-03-20T12:00:00Z')),midnight=sunVector(new Date('2026-03-20T00:00:00Z'));assert(noon[2]>.98);assert(midnight[2]<-.98);assert(Math.abs(Math.hypot(...noon)-1)<.00001);const am=sunVector(new Date('2026-03-20T06:00:00Z'));assert(am[0]>.98);assert.notEqual(moonState(new Date('2026-09-01')).fraction,moonState(new Date('2026-09-15')).fraction);});
